### ISSUE TITLE
isCurrency is removed in mendix 8

### ISSUE THREAD

**Issue by JamesRamm** [AuraQ/AutoCompleteForMendix#51]
the `isCurrency` method of MxMetaObject has been removed in mendix 8, meaning this widget crashes due to line 867 of AutoCompleteForMendix.js

According to release notes, functions deprecated in Mx 7 were removed in v3.0. 

I suggest to remove all uses of ``isCurrency``

**Comment by lindski** [comment]
This has now been fixed in version 5 of the widget

**Comment by jvink** [comment]
Using version 5, and this issue is still not fixed. I also see the isCurrency method still being used in the source code: https://github.com/AuraQ/AutoCompleteForMendix/blob/v3/src/AutoCompleteForMendix/widget/AutoCompleteForMendix.js

![image](https://user-images.githubusercontent.com/27773080/65579232-a68ef600-df77-11e9-86e8-479536359168.png)

**Comment by lindski** [comment]
Hi, you have linked to the source code for version 3 of the widget... have you definitely updated your project to version 5?

Version 5 of the widget now contains the following

`( obj.isCurrency && obj.isCurrency(attr) )`

which first tests for the availability of isCurrency before attempting to execute it. This is required for backwards compatibility with version 7

**Comment by jvink** [comment]
![image](https://user-images.githubusercontent.com/27773080/65584552-587ef000-df81-11e9-9018-14b00b8add3d.png)
Yes, we are using version 5 of the widget.
![image](https://user-images.githubusercontent.com/27773080/65584645-7ea49000-df81-11e9-9f1e-f734e7f39c43.png)
Looks like it is still using the old version? This is what the code looks likes when I check the /widgets directory.

**Comment by lindski** [comment]
I've just downloaded version 5 from the app store into v8.0.0 and it is showing the correct version (with the updated source).

What version of Mendix are you using? Maybe you could try deleting the widget from your project and attempting to download again?

**Comment by jvink** [comment]
Sorry, this seemed to be a Mendix problem. Mendix did not recognise the updated widget. After a while it finally updated the widgets correctly. Thanks for the quick response!
